### ISSUE TITLE
Unsired NPE

### ISSUE THREAD

**Issue by emerald000** [TheStonedTurtle/Loot-Logger#23]
After trading in an Unsired, I get the following error every game tick:

```
WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at thestonedturtle.lootlogger.LootLoggerPlugin.hasUnsiredWidgetUpdated(LootLoggerPlugin.java:354)
	at thestonedturtle.lootlogger.LootLoggerPlugin.onGameTick(LootLoggerPlugin.java:335)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:183)
	at client.px(client.java:25897)
	at client.ak(client.java)
	at ba.d(ba.java:361)
	at ba.run(ba.java:315)
	at java.lang.Thread.run(Thread.java:748)
```

I got a whip if it matters.

**Comment by TheStonedTurtle** [comment]
Fixed in commit 04d275c4373ee7902cf99778193aa689c4e94803 . Thanks for reporting <3
